version: '3.9'
services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    # command: bash -c "service cron start && python manage.py crontab add && python manage.py runserver 0.0.0.0:8000"
    container_name: backend
    restart: always
    ports:
      - 8000:8000
    links:
      - redis
      - frontend
    volumes:
      - .:/app  
  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    restart: always
    ports: 
      - 8080:80
    volumes: 
      - .:/frontend
      - '/frontend/node_modules'
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - 6379:6379
    volumes:
      - ./config/redis.conf:/redis.conf
    command: [ "redis-server", "/redis.conf" ]